export const ACCESS_CHAT_REQUEST = "ACCESS_CHAT_REQUEST";
export const ACCESS_CHAT_SUCCESS = "ACCESS_CHAT_SUCCESS";
export const ACCESS_CHAT_FAIL = "ACCESS_CHAT_FAIL";

export const FETCH_CHATS_REQUEST = "FETCH_CHATS_REQUEST";
export const FETCH_CHATS_SUCCESS = "FETCH_CHATS_SUCCESS";
export const FETCH_CHATS_FAIL = "FETCH_CHATS_FAIL";

export const CREATE_GROUP_CHAT_REQUEST = "CREATE_GROUP_CHAT_REQUEST";
export const CREATE_GROUP_CHAT_SUCCESS = "CREATE_GROUP_CHAT_SUCCESS";
export const CREATE_GROUP_CHAT_FAIL = "CREATE_GROUP_CHAT_FAIL";
