export const ACCESS_CHAT_REQUEST = "ACCESS_CHAT_REQUEST";
export const ACCESS_CHAT_SUCCESS = "ACCESS_CHAT_SUCCESS";
export const ACCESS_CHAT_FAIL = "ACCESS_CHAT_FAIL";

export const FETCH_CHATS_REQUEST = "FETCH_CHATS_REQUEST";
export const FETCH_CHATS_SUCCESS = "FETCH_CHATS_SUCCESS";
export const FETCH_CHATS_FAIL = "FETCH_CHATS_FAIL";

export const CREATE_GROUP_CHAT_REQUEST = "CREATE_GROUP_CHAT_REQUEST";
export const CREATE_GROUP_CHAT_SUCCESS = "CREATE_GROUP_CHAT_SUCCESS";
export const CREATE_GROUP_CHAT_FAIL = "CREATE_GROUP_CHAT_FAIL";

export const UPDATE_GROUP_CHAT_REQUEST = "UPDATE_GROUP_CHAT_REQUEST";
export const UPDATE_GROUP_CHAT_SUCCESS = "UPDATE_GROUP_CHAT_SUCCESS";
export const UPDATE_GROUP_CHAT_FAIL = "UPDATE_GROUP_CHAT_FAIL";

export const DELETE_GROUP_CHAT_REQUEST = "DELETE_GROUP_CHAT_REQUEST";
export const DELETE_GROUP_CHAT_SUCCESS = "DELETE_GROUP_CHAT_SUCCESS";
export const DELETE_GROUP_CHAT_FAIL = "DELETE_GROUP_CHAT_FAIL";

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";

export const ALL_MESSAGES_REQUEST = "ALL_MESSAGES_REQUEST";
export const ALL_MESSAGES_SUCCESS = "ALL_MESSAGES_SUCCESS";
export const ALL_MESSAGES_FAIL = "ALL_MESSAGES_FAIL";

export const DELETE_NORMAL_CHAT_REQUEST = "DELETE_NORMAL_CHAT_REQUEST";
export const DELETE_NORMAL_CHAT_SUCCESS = "DELETE_NORMAL_CHAT_SUCCESS";
export const DELETE_NORMAL_CHAT_FAIL = "DELETE_NORMAL_CHAT_FAIL";
