export const SEND_FOLLOW_REQUEST = "SEND_FOLLOW_REQUEST";
export const SEND_FOLLOW_SUCCESS = "SEND_FOLLOW_SUCCESS";
export const SEND_FOLLOW_FAIL = "SEND_FOLLOW_FAIL";

export const ACCEPT_FOLLOW_REQUEST = "ACCEPT_FOLLOW_REQUEST";
export const ACCEPT_FOLLOW_SUCCESS = "ACCEPT_FOLLOW_SUCCESS";
export const ACCEPT_FOLLOW_FAIL = "ACCEPT_FOLLOW_FAIL";

export const REJECT_FOLLOW_REQUEST = "REJECT_FOLLOW_REQUEST";
export const REJECT_FOLLOW_SUCCESS = "REJECT_FOLLOW_SUCCESS";
export const REJECT_FOLLOW_FAIL = "REJECT_FOLLOW_FAIL";

export const CHECK_SENT_REQUEST = "CHECK_SENT_REQUEST";
export const CHECK_SENT_SUCCESS = "CHECK_SENT_SUCCESS";
export const CHECK_SENT_FAIL = "CHECK_SENT_FAIL";
