export const SEND_FOLLOW_REQUEST = "SEND_FOLLOW_REQUEST";
export const SEND_FOLLOW_SUCCESS = "SEND_FOLLOW_SUCCESS";
export const SEND_FOLLOW_FAIL = "SEND_FOLLOW_FAIL";

export const ACCEPT_FOLLOW_REQUEST = "ACCEPT_FOLLOW_REQUEST";
export const ACCEPT_FOLLOW_SUCCESS = "ACCEPT_FOLLOW_SUCCESS";
export const ACCEPT_FOLLOW_FAIL = "ACCEPT_FOLLOW_FAIL";

export const REJECT_FOLLOW_REQUEST = "REJECT_FOLLOW_REQUEST";
export const REJECT_FOLLOW_SUCCESS = "REJECT_FOLLOW_SUCCESS";
export const REJECT_FOLLOW_FAIL = "REJECT_FOLLOW_FAIL";

export const CHECK_SENT_REQUEST = "CHECK_SENT_REQUEST";
export const CHECK_SENT_SUCCESS = "CHECK_SENT_SUCCESS";
export const CHECK_SENT_FAIL = "CHECK_SENT_FAIL";

export const ALL_REQUESTS_REQUEST = "ALL_REQUESTS_REQUEST";
export const ALL_REQUESTS_SUCCESS = "ALL_REQUESTS_SUCCESS";
export const ALL_REQUESTS_FAIL = "ALL_REQUESTS_FAIL";

export const ALREADY_FOLLOWING_REQUEST = "ALREADY_FOLLOWING_REQUEST";
export const ALREADY_FOLLOWING_SUCCESS = "ALREADY_FOLLOWING_SUCCESS";
export const ALREADY_FOLLOWING_FAIL = "ALREADY_FOLLOWING_FAIL";

export const GET_FOLLOWING_REQUEST = "GET_FOLLOWING_REQUEST";
export const GET_FOLLOWING_SUCCESS = "GET_FOLLOWING_SUCCESS";
export const GET_FOLLOWING_FAIL = "GET_FOLLOWING_FAIL";
